#!/usr/bin/env python

"""Script used to retrieve the type of a file
"""

from __future__ import print_function
import xml.etree.ElementTree as ET
import sys
import os


def get_file_type(filename):
    """Parse file and return its type
    """
    tree = ET.parse(filename)
    root = tree.getroot()
    if root.tag == 'sdf':
        print('world')
    elif root.tag == 'drone':
        print('drone')
    elif root.tag == 'actor' or root.tag == 'model':
        print('actor')
    else:
        print('unknown')


def main():
    """Main function
    """
    if len(sys.argv) < 2:
        sys.stderr.write("No file given\n")
        sys.exit(1)
    filename = sys.argv[1]

    if os.path.isfile(filename):
        get_file_type(filename)

if __name__ == "__main__":
    try:
        main()
    except:
        sys.exit(1)
