#!/bin/bash

export ROS_IP=172.17.0.2
export ROS_MASTER_URI=http://172.17.0.2:11311

cd /home/bebop2/Desktop
sudo ./sphinx.sh
sleep 10
gnome-terminal -- ./bebop_autonomy.sh
cd /home/bebop2/catkin_ws/src/g2rr/scripts
python3 g2r_republisher_node.pyc bebop2
